# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-10 16:04
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NodeData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info_json', jsonfield.fields.JSONField()),
                ('nettotals_json', jsonfield.fields.JSONField()),
            ],
        ),
    ]
