# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-10 16:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('nodedata', '0002_auto_20160510_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawnodedata',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 5, 10, 16, 14, 2, 253942, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
