# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-11 01:49
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('nodedata', '0003_rawnodedata_datetime_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawnodedata',
            name='peerinfo_json',
            field=jsonfield.fields.JSONField(default=None),
            preserve_default=False,
        ),
    ]
