# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-11 13:53
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('nodedata', '0004_rawnodedata_peerinfo_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawnodedata',
            name='networkinfo_json',
            field=jsonfield.fields.JSONField(default=None),
            preserve_default=False,
        ),
    ]
