# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-12 00:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodedata', '0006_peer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peer',
            name='peer_json',
        ),
        migrations.AddField(
            model_name='peer',
            name='ip',
            field=models.CharField(default='0.0.0.0', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='peer',
            name='port',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
