# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-12 17:36
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('nodedata', '0007_auto_20160512_0240'),
    ]

    operations = [
        migrations.AddField(
            model_name='peer',
            name='peer_json',
            field=jsonfield.fields.JSONField(default=None),
            preserve_default=False,
        ),
    ]
