# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-12 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodedata', '0008_peer_peer_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawnodedata',
            name='node_up',
            field=models.BooleanField(default=True),
        ),
    ]
